# Generated by Django 5.2.5 on 2025-08-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employees_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeModel',
        ),
    ]
